# Generated by Django 5.0.6 on 2024-08-16 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer_contact_phone_number_contact_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customervideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('videofile', models.FileField(upload_to='customervideos/')),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cvideos', to='app.customer')),
            ],
        ),
    ]
