# Generated by Django 5.0.6 on 2024-08-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customervideos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customervideos',
            new_name='customer_videos',
        ),
    ]
