# Generated by Django 5.1.1 on 2024-09-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_customervideos_customer_videos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerproduct',
            options={},
        ),
    ]
