# Generated by Django 5.1.1 on 2024-09-04 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customerproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_videos',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app.customer'),
        ),
    ]
